### ISSUE TITLE
cool library, but I have a question.

### ISSUE THREAD

**Issue by glennposadas** [masasron/firebase-php#1]
Hi, I find this quite easy to use for a newbie like me. I am an iOS developer and I'm very new to web PHP. I have a CMS which is now integrated to Firebase but only the authentication functionality. Right now I can fetch some data from my Firebase database with the use of PHP. I don't really know how to model the data from my database in web, so I tried searching for this. My question is: does this library work with the new version of Firebase? Thanks @masasron .

Glenn

**Comment by masasron** [comment]
Hi @glennposadas, unfortunately is answer is no, the library is using the old authentication method.  However authentication and all other functionality still works on any "new" Firebase project.
